### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by ghost** [rohityadav-sas/Hamster-KeyGen#3]
I get this error :
![image](https://github.com/user-attachments/assets/5547ad31-d148-45ea-85c0-4ad8cd708a7d)
How do i fix it?

**Comment by rohityadav-sas** [comment]
> I get this error :
> ![image](https://github.com/user-attachments/assets/5547ad31-d148-45ea-85c0-4ad8cd708a7d)
> How do i fix it?

Maybe a temporary error, restart the server.
