### ISSUE TITLE
error: [polling_error] {"code":"EFATAL","message":"EFATAL: Telegram Bot Token not provided!"}

### ISSUE THREAD

**Issue by sacoq** [rohityadav-sas/Hamster-KeyGen#4]
error: [polling_error] {"code":"EFATAL","message":"EFATAL: Telegram Bot Token not provided!"}

**Comment by rohityadav-sas** [comment]
You have to create your own telegram bot and put the token in the .env file

**Comment by sacoq** [comment]
yes, dont work
![image](https://github.com/user-attachments/assets/fc8077f3-755c-4c5a-8c6d-34b09a2c2446)
